import React, { useState, useEffect } from 'react';
import { useQuery, useMutation } from '@apollo/client';
import {
  Box,
  CircularProgress,
  Typography,
  Button,
  Alert,
  Sheet,
  Divider,
  Switch,
  Select,
  Option,
  Input,
  FormLabel,
  FormControl,
} from '@mui/joy';
import {
  EXPORT_KOMETA,
  GET_KOMETA_SCHEDULE,
  UPDATE_KOMETA_SCHEDULE,
  SET_MDBLIST_API_KEY,
  GET_APP_INFO,
} from '../../graphql/queries';

interface ExportedList {
  name: string;
  type: string;
  movieCount: number;
  mdblistUrl: string | null;
}

interface ScheduleData {
  enabled: boolean;
  frequency: string;
  dailyTime: string;
  lastRunAt: string | null;
  mdblistApiKeySet: boolean;
  exportedLists: ExportedList[];
}

function generatePreviewYaml(lists: ExportedList[]): string {
  const today = new Date().toISOString().split('T')[0];
  let yaml = `## MovieNight Collections — preview ${today}\n`;
  yaml += `## Generated by MovieNight. Do not edit manually.\n`;
  yaml += `collections:\n`;
  for (const list of lists) {
    const url = list.mdblistUrl || '<created on first export>';
    yaml += `  "${list.name}":\n`;
    yaml += `    mdblist_list: ${url}\n`;
    yaml += `    collection_order: custom\n`;
    yaml += `    sync_mode: sync\n`;
    yaml += `    radarr_add_missing: true\n`;
    yaml += `    radarr_search: true\n`;
    yaml += `    visible_home: true\n`;
    yaml += `    visible_shared: true\n`;
    yaml += `    summary: "MovieNight — ${list.name} — exported ${today}"\n`;
  }
  return yaml;
}

export const KometaExport: React.FC = () => {
  const [exportKometa, { loading: exporting }] = useMutation(EXPORT_KOMETA);

  const { data: scheduleData, loading: scheduleLoading } = useQuery(GET_KOMETA_SCHEDULE, {
    fetchPolicy: 'cache-and-network',
  });
  const { data: appInfoData } = useQuery(GET_APP_INFO, { fetchPolicy: 'cache-first' });
  const isProd = appInfoData?.appInfo?.isProduction ?? true;
  const [updateSchedule, { loading: savingSchedule }] = useMutation(UPDATE_KOMETA_SCHEDULE);

  const [setMdblistApiKey, { loading: savingApiKey }] = useMutation(SET_MDBLIST_API_KEY, {
    refetchQueries: [{ query: GET_KOMETA_SCHEDULE }],
  });

  const [copied, setCopied] = useState(false);
  const [exportResult, setExportResult] = useState<
    | {
        path: string;
        triggered: boolean;
        triggerError?: string;
        lists: ExportedList[];
      }
    | { error: string }
    | null
  >(null);

  // Local form state for schedule
  const [schedEnabled, setSchedEnabled] = useState(false);
  const [schedFrequency, setSchedFrequency] = useState('daily');
  const [schedDailyTime, setSchedDailyTime] = useState('03:00');
  const [schedSaveResult, setSchedSaveResult] = useState<'saved' | { error: string } | null>(null);

  // MDBList API key state
  const [apiKeyInput, setApiKeyInput] = useState('');
  const [apiKeySaveResult, setApiKeySaveResult] = useState<'saved' | { error: string } | null>(
    null,
  );

  // Sync form state when server data loads
  useEffect(() => {
    const s: ScheduleData | undefined = scheduleData?.kometaSchedule;
    if (s) {
      setSchedEnabled(s.enabled);
      setSchedFrequency(s.frequency);
      setSchedDailyTime(s.dailyTime);
    }
  }, [scheduleData]);

  const exportedLists: ExportedList[] = scheduleData?.kometaSchedule?.exportedLists ?? [];
  const yaml = exportedLists.length > 0 ? generatePreviewYaml(exportedLists) : '';

  const handleCopy = async () => {
    await navigator.clipboard.writeText(yaml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([yaml], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'movienight.yml';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExport = async () => {
    setExportResult(null);
    try {
      const { data: result } = await exportKometa();
      const { filePath, triggered, triggerError, lists } = result.exportKometa;
      setExportResult({ path: filePath, triggered, triggerError, lists });
    } catch (err: any) {
      setExportResult({ error: err.message });
    }
  };

  const handleSaveSchedule = async () => {
    setSchedSaveResult(null);
    try {
      await updateSchedule({
        variables: {
          enabled: schedEnabled,
          frequency: schedFrequency,
          dailyTime: schedDailyTime,
        },
      });
      setSchedSaveResult('saved');
      setTimeout(() => setSchedSaveResult(null), 3000);
    } catch (err: any) {
      setSchedSaveResult({ error: err.message });
    }
  };

  const handleSaveApiKey = async () => {
    setApiKeySaveResult(null);
    try {
      await setMdblistApiKey({ variables: { apiKey: apiKeyInput } });
      setApiKeyInput('');
      setApiKeySaveResult('saved');
      setTimeout(() => setApiKeySaveResult(null), 3000);
    } catch (err: any) {
      setApiKeySaveResult({ error: err.message });
    }
  };

  const lastRun: string | null = scheduleData?.kometaSchedule?.lastRunAt ?? null;
  const apiKeySet: boolean = scheduleData?.kometaSchedule?.mdblistApiKeySet ?? false;

  if (scheduleLoading && !scheduleData) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
        <CircularProgress size="md" color="primary" />
      </Box>
    );
  }

  return (
    <Box>
      <Typography level="body-sm" sx={{ color: 'text.tertiary', mb: 2 }}>
        Exports combined and solo movie lists to MDBList and writes a Kometa collection file.
        Combined lists are ranked by averaged Elo. Solo lists contain movies all connections passed
        on. <strong>Write to Kometa</strong> syncs lists and writes to{' '}
        <code>KOMETA_COLLECTIONS_PATH</code>.
      </Typography>

      {exportResult && (
        <Alert color={'error' in exportResult ? 'danger' : 'success'} sx={{ mb: 2 }}>
          {'error' in exportResult ? (
            exportResult.error
          ) : (
            <Box>
              <Typography level="body-sm">
                Written to {exportResult.path} — {exportResult.lists.length} list
                {exportResult.lists.length !== 1 ? 's' : ''}
              </Typography>
              {exportResult.lists.map((l) => (
                <Typography key={l.name} level="body-xs" sx={{ mt: 0.25, opacity: 0.85 }}>
                  {l.type === 'combined' ? '\u{1F91D}' : '\u{1F3AC}'} {l.name} ({l.movieCount} movie
                  {l.movieCount !== 1 ? 's' : ''})
                </Typography>
              ))}
              {exportResult.triggered && (
                <Typography level="body-xs" sx={{ mt: 0.5, opacity: 0.8 }}>
                  Kometa run triggered.
                </Typography>
              )}
              {exportResult.triggerError && (
                <Typography level="body-xs" sx={{ mt: 0.5, color: 'warning.600' }}>
                  Could not trigger Kometa run: {exportResult.triggerError}
                </Typography>
              )}
            </Box>
          )}
        </Alert>
      )}

      {!isProd && (
        <Alert color="warning" sx={{ mb: 2 }}>
          <Typography level="body-sm">
            <strong>Dev/test environment:</strong> Direct write to Kometa and scheduled exports are
            disabled to protect production systems.
          </Typography>
        </Alert>
      )}

      <Box sx={{ display: 'flex', gap: 1, mb: 2, flexWrap: 'wrap' }}>
        <Button
          size="sm"
          variant="solid"
          color="primary"
          loading={exporting}
          onClick={handleExport}
          disabled={!isProd}
        >
          Write to Kometa
        </Button>
        {yaml && (
          <>
            <Button size="sm" variant="outlined" color="neutral" onClick={handleDownload}>
              Download .yml
            </Button>
            <Button
              size="sm"
              variant="outlined"
              color={copied ? 'success' : 'neutral'}
              onClick={handleCopy}
            >
              {copied ? 'Copied!' : 'Copy to clipboard'}
            </Button>
          </>
        )}
      </Box>

      {exportedLists.length > 0 && (
        <>
          <Typography level="title-sm" fontWeight={700} sx={{ mb: 1 }}>
            {exportedLists.length} list{exportedLists.length !== 1 ? 's' : ''} configured
          </Typography>
          {exportedLists.map((l) => (
            <Typography key={l.name} level="body-xs" sx={{ color: 'text.tertiary', mb: 0.25 }}>
              {l.type === 'combined' ? '\u{1F91D}' : '\u{1F3AC}'} {l.name}
              {l.mdblistUrl && (
                <>
                  {' — '}
                  <a href={l.mdblistUrl} target="_blank" rel="noopener noreferrer">
                    MDBList
                  </a>
                </>
              )}
            </Typography>
          ))}
        </>
      )}

      {yaml && (
        <Sheet
          variant="outlined"
          sx={{
            borderRadius: 'md',
            borderColor: 'var(--mn-border-vis)',
            overflow: 'auto',
            maxHeight: 480,
            mt: 2,
          }}
        >
          <Box
            component="pre"
            sx={{
              m: 0,
              p: 2,
              fontSize: '0.8rem',
              fontFamily: 'monospace',
              lineHeight: 1.6,
              color: 'text.primary',
              whiteSpace: 'pre',
            }}
          >
            {yaml}
          </Box>
        </Sheet>
      )}

      <Divider sx={{ my: 3 }} />

      <Typography level="title-sm" fontWeight={700} sx={{ mb: 2 }}>
        MDBList API Key
      </Typography>

      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5, maxWidth: 380, mb: 0 }}>
        <Typography level="body-xs" sx={{ color: 'text.tertiary' }}>
          Required for syncing movies to MDBList. Get a free key at{' '}
          <a href="https://mdblist.com/preferences/" target="_blank" rel="noopener noreferrer">
            mdblist.com/preferences
          </a>
          .
        </Typography>

        <Typography level="body-xs" sx={{ color: apiKeySet ? 'success.600' : 'warning.600' }}>
          {apiKeySet ? 'API key is configured.' : 'No API key set — export will fail.'}
        </Typography>

        <FormControl>
          <FormLabel>{apiKeySet ? 'Update API key' : 'Enter API key'}</FormLabel>
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Input
              size="sm"
              type="password"
              placeholder="mdblist_api_key"
              value={apiKeyInput}
              onChange={(e) => setApiKeyInput(e.target.value)}
              sx={{ flex: 1 }}
            />
            <Button
              size="sm"
              variant="outlined"
              color="primary"
              loading={savingApiKey}
              onClick={handleSaveApiKey}
              disabled={!apiKeyInput.trim()}
            >
              Save
            </Button>
          </Box>
        </FormControl>

        {apiKeySaveResult && (
          <Alert color={apiKeySaveResult === 'saved' ? 'success' : 'danger'} size="sm">
            {apiKeySaveResult === 'saved'
              ? 'API key saved'
              : (apiKeySaveResult as { error: string }).error}
          </Alert>
        )}
      </Box>

      <Divider sx={{ my: 3 }} />

      <Typography level="title-sm" fontWeight={700} sx={{ mb: 2 }}>
        Scheduled Export
      </Typography>

      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, maxWidth: 380 }}>
        <FormControl orientation="horizontal" sx={{ justifyContent: 'space-between' }}>
          <FormLabel>
            Enable scheduled export
            {!isProd && (
              <Typography level="body-xs" sx={{ color: 'warning.600', ml: 1 }}>
                (production only)
              </Typography>
            )}
          </FormLabel>
          <Switch
            checked={schedEnabled}
            onChange={(e) => setSchedEnabled(e.target.checked)}
            size="sm"
            disabled={!isProd}
          />
        </FormControl>

        <FormControl>
          <FormLabel>Frequency</FormLabel>
          <Select
            size="sm"
            value={schedFrequency}
            onChange={(_, v) => v && setSchedFrequency(v)}
            disabled={!schedEnabled}
          >
            <Option value="hourly">Hourly (at :00)</Option>
            <Option value="daily">Daily</Option>
          </Select>
        </FormControl>

        {schedFrequency === 'daily' && (
          <FormControl>
            <FormLabel>Time (24-hour)</FormLabel>
            <Input
              size="sm"
              type="time"
              value={schedDailyTime}
              onChange={(e) => setSchedDailyTime(e.target.value)}
              disabled={!schedEnabled}
              sx={{ maxWidth: 140 }}
            />
          </FormControl>
        )}

        {schedSaveResult && (
          <Alert color={schedSaveResult === 'saved' ? 'success' : 'danger'} size="sm">
            {schedSaveResult === 'saved'
              ? 'Schedule saved'
              : (schedSaveResult as { error: string }).error}
          </Alert>
        )}

        {lastRun && (
          <Typography level="body-xs" sx={{ color: 'text.tertiary' }}>
            Last scheduled run: {new Date(lastRun).toLocaleString()}
          </Typography>
        )}

        <Box>
          <Button
            size="sm"
            variant="outlined"
            color="primary"
            loading={savingSchedule}
            onClick={handleSaveSchedule}
            disabled={!isProd}
          >
            Save Schedule
          </Button>
        </Box>
      </Box>
    </Box>
  );
};
