import fs from 'fs';
import path from 'path';
import pool from './db';

// ── Borda rank recalculation ───────────────────────────────────────────────────

async function recalculateBordaRanks(): Promise<void> {
  try {
    const moviesResult = await pool.query(
      'SELECT id FROM movies WHERE watched_at IS NULL ORDER BY id'
    );
    const movieIds: number[] = moviesResult.rows.map((r: any) => r.id);
    if (movieIds.length === 0) return;

    const scores = new Map<number, number>(movieIds.map((id) => [id, 0]));

    const rankingsResult = await pool.query(
      `SELECT umr.user_id, umr.movie_id
       FROM user_movie_rankings umr
       JOIN movies m ON m.id = umr.movie_id
       WHERE m.watched_at IS NULL
       ORDER BY umr.user_id, umr.rank ASC`
    );

    // Group by user, apply Borda points (position 0 = top, earns most points)
    const byUser = new Map<number, number[]>();
    for (const row of rankingsResult.rows) {
      if (!byUser.has(row.user_id)) byUser.set(row.user_id, []);
      byUser.get(row.user_id)!.push(row.movie_id);
    }
    for (const [, userMovieIds] of byUser) {
      const n = userMovieIds.length;
      for (let i = 0; i < n; i++) {
        const id = userMovieIds[i];
        if (scores.has(id)) scores.set(id, scores.get(id)! + (n - i));
      }
    }

    // Batch update movies.rank with Borda scores
    for (const [movieId, score] of scores) {
      await pool.query('UPDATE movies SET rank = $1 WHERE id = $2', [score, movieId]);
    }

    console.log(`[Borda] Recalculated rankings for ${movieIds.length} movie(s)`);
  } catch (err) {
    console.error('[Borda] Recalculation failed:', err);
  }
}

let bordaDebounceTimer: ReturnType<typeof setTimeout> | null = null;

export function scheduleBordaRecalculation(): void {
  if (bordaDebounceTimer) clearTimeout(bordaDebounceTimer);
  bordaDebounceTimer = setTimeout(async () => {
    bordaDebounceTimer = null;
    await recalculateBordaRanks();
  }, 10000);
  if (bordaDebounceTimer.unref) bordaDebounceTimer.unref();
}

// ── Kometa export scheduler ────────────────────────────────────────────────────

let scheduledTimeout: ReturnType<typeof setTimeout> | null = null;

async function runKometaExportScheduled(): Promise<void> {
  const collectionsPath = process.env.KOMETA_COLLECTIONS_PATH;
  if (!collectionsPath) {
    console.error('[Kometa Scheduler] KOMETA_COLLECTIONS_PATH not configured, skipping');
    return;
  }

  try {
    const settingsResult = await pool.query('SELECT * FROM kometa_schedule WHERE id = 1');
    if (settingsResult.rows.length === 0 || !settingsResult.rows[0].enabled) return;
    const settings = settingsResult.rows[0];

    const moviesResult = await pool.query(
      'SELECT title, tmdb_id, rank FROM movies WHERE watched_at IS NULL ORDER BY rank DESC NULLS LAST, date_submitted ASC'
    );
    const movies = moviesResult.rows;
    const matched = movies.filter((m: any) => m.tmdb_id != null);

    if (matched.length === 0) {
      console.log('[Kometa Scheduler] No movies with TMDB IDs, skipping export');
    } else {
      const name = settings.collection_name || 'MovieNight Watchlist';
      const today = new Date().toISOString().split('T')[0];
      const idLines = matched.map((m: any) => `      - ${m.tmdb_id}`).join('\n');
      const yaml =
        `## MovieNight Collection — auto-exported ${today}\n` +
        `## Generated by MovieNight scheduler. Do not edit manually.\n` +
        `collections:\n` +
        `  ${name}:\n` +
        `    tmdb_movie:\n` +
        `${idLines}\n` +
        `    collection_order: custom\n` +
        `    sync_mode: sync\n` +
        `    radarr_add_missing: true\n` +
        `    radarr_search: true\n` +
        `    visible_home: true\n` +
        `    visible_shared: true\n` +
        `    summary: "MovieNight watchlist — exported ${today}"\n`;

      const filePath = path.join(collectionsPath, 'movienight.yml');
      await fs.promises.writeFile(filePath, yaml, 'utf8');

      await pool.query('UPDATE kometa_schedule SET last_run_at = NOW() WHERE id = 1');

      await pool.query(
        'INSERT INTO audit_logs (actor_id, action, target_type, target_id, metadata, ip_address) VALUES ($1, $2, $3, $4, $5, $6)',
        [
          null,
          'KOMETA_SCHEDULE_EXPORT',
          'kometa',
          filePath,
          JSON.stringify({ count: matched.length, skipped: movies.length - matched.length, scheduled: true }),
          'scheduler',
        ]
      );

      console.log(`[Kometa Scheduler] Exported ${matched.length} movies to ${filePath}`);
    }
  } catch (err) {
    console.error('[Kometa Scheduler] Export failed:', err);
  }
}

function getMsUntilNext(frequency: string, dailyTime: string): number {
  const now = new Date();

  if (frequency === 'hourly') {
    const next = new Date(now);
    next.setMinutes(0, 0, 0);
    next.setHours(next.getHours() + 1);
    return next.getTime() - now.getTime();
  }

  // daily: parse HH:MM
  const [hours, minutes] = dailyTime.split(':').map(Number);
  const next = new Date(now);
  next.setHours(hours, minutes, 0, 0);
  if (next.getTime() <= now.getTime()) {
    next.setDate(next.getDate() + 1);
  }
  return next.getTime() - now.getTime();
}

function scheduleNext(frequency: string, dailyTime: string): void {
  if (scheduledTimeout) {
    clearTimeout(scheduledTimeout);
    scheduledTimeout = null;
  }

  const ms = getMsUntilNext(frequency, dailyTime);
  const mins = Math.round(ms / 60000);
  console.log(`[Kometa Scheduler] Next export in ~${mins} minute(s)`);

  scheduledTimeout = setTimeout(async () => {
    scheduledTimeout = null;
    // Re-read settings in case they changed
    const result = await pool.query('SELECT * FROM kometa_schedule WHERE id = 1');
    if (result.rows.length > 0 && result.rows[0].enabled) {
      await runKometaExportScheduled();
      scheduleNext(result.rows[0].frequency, result.rows[0].daily_time);
    }
  }, ms);

  // Allow Node process to exit even if timer is pending
  if (scheduledTimeout.unref) scheduledTimeout.unref();
}

export async function initScheduler(): Promise<void> {
  // Borda recalculation runs in all environments
  await recalculateBordaRanks();
  const bordaInterval = setInterval(() => recalculateBordaRanks(), 5 * 60 * 1000);
  if (bordaInterval.unref) bordaInterval.unref();
  console.log('[Borda] Periodic recalculation started (every 5 minutes)');

  if (process.env.NODE_ENV !== 'production') {
    console.log('[Kometa Scheduler] Disabled (non-production environment)');
    return;
  }

  try {
    const result = await pool.query('SELECT * FROM kometa_schedule WHERE id = 1');
    if (result.rows.length === 0) return;
    const settings = result.rows[0];

    if (settings.enabled) {
      console.log(`[Kometa Scheduler] Starting (${settings.frequency})`);
      scheduleNext(settings.frequency, settings.daily_time);
    } else {
      console.log('[Kometa Scheduler] Disabled, not starting');
    }
  } catch (err) {
    console.error('[Kometa Scheduler] Failed to initialize:', err);
  }
}

export function rescheduleKometa(enabled: boolean, frequency: string, dailyTime: string): void {
  if (process.env.NODE_ENV !== 'production') {
    console.log('[Kometa Scheduler] Reschedule skipped (non-production environment)');
    return;
  }

  if (scheduledTimeout) {
    clearTimeout(scheduledTimeout);
    scheduledTimeout = null;
  }

  if (enabled) {
    console.log(`[Kometa Scheduler] Rescheduling (${frequency})`);
    scheduleNext(frequency, dailyTime);
  } else {
    console.log('[Kometa Scheduler] Disabled');
  }
}
